services:
  notion_voice_assistant:
    build:
      context: ./app
    depends_on:
      - whisper_api 
      - db
    ports:
      - 3000:3000
    networks:
      - app
      - ai
  whisper_api:
    build:
      context: ./whisper-api
    ports:
      - 8000:8000 
    networks:
    - ai
  db: 
    image: postgres:16.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports: 
     - 5432:5432
    networks:
      - app
networks:
  ai:
  app: